groups/urls.py
from django.conf.urls import url

from . import views

app_name = 'groups'

urlpatterns = [
    url(r"^$", views.ListGroups.as_view(),
        name="all"),
    url(r"^new/$", views.CreateGroup.as_view(),
        name="create"),
    url(r"^posts/in/(?P<slug>[-\w]+)/$", views.SingleGroup.as_view(),
        name="single"),
    url(r"join/(?P<slug>[-\w]+)/$", views.JoinGroup.as_view(),
        name="join"),
    url(r"leave/(?P<slug>[-\w]+)/$", views.LeaveGroup.as_view(),
        name="leave"),
]

posts/urls.py
from django.conf.urls import url

from . import views

app_name = 'posts'

urlpatterns = [
    url(r"^$", views.PostList.as_view(),
        name="all"),
    url(r"new/$", views.CreatePost.as_view(),
        name="create"),
    url(r"new/(?P<slug>[-\w]+)/$", views.CreatePost.as_view(),
        name="create"),
    url(r"by/(?P<username>[-\w]+)/$", views.UserPosts.as_view(),
        name="for_user"),
    url(r"by/(?P<username>[-\w]+)/(?P<pk>\d+)/$", views.PostDetail.as_view(),
        name="single"),
    url(r"delete/(?P<pk>\d+)/$", views.DeletePost.as_view(),
        name="delete"),
]

simplesocial/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

from . import views

urlpatterns = [
    url(r"^$", views.WelcomeView.as_view(), name="home"),
    url(r"^thanks/$", views.ThanksPage.as_view(), name="thanks"),
    url(r"^admin/", admin.site.urls),
    url(r"^accounts/", include("accounts.urls", namespace="accounts")),
    url(r"^accounts/", include("django.contrib.auth.urls")),
    url(r"^posts/", include("posts.urls", namespace="posts")),
    url(r"^groups/", include("groups.urls", namespace="groups")),
    url(r"^tech_news/", include("tech_news.urls", namespace="tech_news")),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r"^rest_api/", include("rest_api.urls", namespace="rest_api"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

groups/models.py
# from django.conf import settings
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.text import slugify
from django.contrib.auth import get_user_model
import misaka
from django import template
User = get_user_model()

register = template.Library()


class Group(models.Model):
    name = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(allow_unicode=True, unique=True)
    description = models.TextField(blank=True, default='')
    description_html = models.TextField(editable=False, default='', blank=True)
    members = models.ManyToManyField(User, through="GroupMember")
    image = models.ImageField(upload_to='images/', null=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        self.description_html = misaka.html(self.description)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("groups:single", kwargs={"slug": self.slug})

    class Meta:
        ordering = ["name"]


class GroupMember(models.Model):
    group = models.ForeignKey(Group, related_name="memberships")
    user = models.ForeignKey(User, related_name='user_groups')

    def __str__(self):
        return self.user.username

    class Meta:
        unique_together = ("group", "user")

groups/forms.py
from django.forms import (Form, CharField, Textarea, ImageField)


class CreateGroupForm(Form):
    name = CharField(max_length=64)
    description = CharField(widget=Textarea, required=False)
    image = ImageField(required=False)

groups/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.urlresolvers import reverse
from django.db import IntegrityError
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.views import generic, View
from django.contrib.auth.models import User, Group

from .forms import CreateGroupForm
from .models import Group, GroupMember


class CreateGroup(LoginRequiredMixin, View):
    def get(self, request):
        form = CreateGroupForm()
        ctx = {'form': form}

        return render(request,
                      template_name='groups/create_group.html',
                      context=ctx)

    def post(self, request):
        form = CreateGroupForm(request.POST, request.FILES)
        if form.is_valid():
            name = form.cleaned_data['name']
            description = form.cleaned_data['description']
            image = form.cleaned_data['image']

            if Group.objects.filter(name=name).exists():
                return HttpResponseRedirect('/object_already_exist')

            Group.objects.create(name=name,
                                 description=description,
                                 image=image)
            return HttpResponseRedirect(reverse('groups:all'))
        return HttpResponseRedirect('/wrong_value')


class SingleGroup(generic.DetailView):
    model = Group


class ListGroups(generic.ListView):
    model = Group


class ListUserGroups(generic.ListView):
    model = Group


class JoinGroup(LoginRequiredMixin, generic.RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        return reverse("groups:single", kwargs={"slug": self.kwargs.get("slug")})

    def get(self, request, *args, **kwargs):
        group = get_object_or_404(Group, slug=self.kwargs.get("slug"))

        try:
            GroupMember.objects.create(user=self.request.user, group=group)
        except IntegrityError:
            messages.warning(self.request, ("Warning, already a member of {}".format(group.name)))
        else:
            messages.success(self.request, "You are now a member of the {} group.".format(group.name))

        return super().get(request, *args, **kwargs)


class LeaveGroup(LoginRequiredMixin, generic.RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        return reverse("groups:single", kwargs={"slug": self.kwargs.get("slug")})

    def get(self, request, *args, **kwargs):

        try:
            membership = GroupMember.objects.filter(
                user=self.request.user,
                group__slug=self.kwargs.get("slug")
            ).get()

        except GroupMember.DoesNotExist:
            messages.warning(
                self.request,
                "You can't leave this group because you aren't in it."
            )
        else:
            membership.delete()
            messages.success(
                self.request,
                "You have successfully left this group."
            )
        return super().get(request, *args, **kwargs)

groups/templates/groups/create_group.html
{% extends 'groups/group_base.html' %}
{% load static %}
{% load bootstrap4 %}
{% block content %}
    <div class="card">
        <div class="card-body">
            <img class="news-img" src="{%  static 'img/logo.png' %}" alt="'No image"
                 style='float:left'>
            <h1>Create A New Group</h1>
        </div>
    </div>
    <div class="card">
        <div class="card-body">
            <form action="{% url 'groups:create' %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {% bootstrap_form form %}
                <input type="submit" value="Create" class="btn btn-primary btn-lg btn-block">
            </form>
        </div>
    </div>
{% endblock %}

groups/templates/groups/group_base.html
{% extends "base.html" %}
{% block content %}
    <div class="container">
        {% block pregroup %}{% endblock %}
        {% block group_content %}{% endblock %}
        {% block postgroup %}{% endblock %}
    </div>

{% endblock %}

groups/templates/groups/group_detail.html
{% extends "groups/group_base.html" %}

{% block pregroup %}
    <div class="card">
        <div class="card-body">
            <img class="news-img" src="{{ group.image.url }}" alt="'No image"
                 style='float:left'>
            <h1 class="card-text">{{ group.name }}</h1>
            <h2> Members: {{ group.members.count }}</h2>
        </div>
        <div class="card-footer">
            <div class="row">
                <div class="col col-md-6">
                    {% if user.is_authenticated %}
                        <a href="{% url 'posts:create' slug=group.slug %}"
                           class="btn btn-primary btn-lg btn-block">Create New Post!</a>
                    {% endif %}
                </div>
                <div class="col col-md-6">
                    {% if user in group.members.all %}
                        <a href="{% url 'groups:leave' slug=group.slug %}"
                           class="btn btn-lg btn-block btn-warning"><span
                                class="glyphicon glyphicon-remove-circle"></span> Leave</a>
                    {% else %}
                        <a href="{% url 'groups:join' slug=group.slug %}"
                           class="btn btn-lg btn-block btn-success">Join</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block group_content %}
    {% if group.posts.count == 0 %}
        <div id="news_field" class="card">
            <div class="card-body">
                <p class="card-text card-description">No posts in this group yet!</p>
            </div>
        </div>
    {% else %}
        {% for post in group.posts.all %}
            {% include "posts/_post.html" %}
        {% endfor %}
    {% endif %}
{% endblock %}

groups/templates/groups/group_list.html
{% extends "groups/group_base.html" %}
{% load staticfiles %}

{% block pregroup %}
    <div class="card">
        <div class="card-body">
            <img class="news-img" src="{% static 'img/logo.png' %}" alt="'No image">
            <h1 class="card-text">Welcome to the Groups Page!</h1>
        </div>
        <div class="card-footer text-muted">
            {% if user.is_authenticated %}
                <a href="{% url 'groups:create' %}" class="btn btn-primary btn-lg btn-block">Create New Group!</a>
            {% else %}
                <h3 class="card-footer-text">Log in to create new groups and posts</h3>
            {% endif %}
        </div>
    </div>
{% endblock %}
{% block group_content %}
    {% for group in object_list %}
        <div id="news_field" class="card">
            <h5 class="card-header">{{ group.name }}</h5>
            <div class="card-body">
                {% if group.image %}
                    <img class="news-img" src="{{ group.image.url }}" alt="'No image">
                {% else %}
                    <img class="news-img" src="{% static 'img/logo.png' %}" alt="'No image">
                {% endif %}
                <h4 class="card-text card-description">{{ group.description_html|safe }}</h4>
                <div id="post-counter">
                    <button type="button" class="btn btn-primary">
                        <span class="badge badge-light">{{ group.posts.count }}</span>
                        post{{ group.posts.count|pluralize }}
                    </button>
                </div>
            </div>
            <div class="card-footer text-muted">
                <a href="{% url 'groups:single' slug=group.slug %}"
                   class="btn btn-primary btn-block hvr-float-shadow">Enter</a>
            </div>
        </div>
    {% endfor %}
{% endblock %}