posts/urls.py
from django.conf.urls import url

from . import views

app_name = 'posts'

urlpatterns = [
    url(r"^$", views.PostList.as_view(),
        name="all"),
    url(r"new/$", views.CreatePost.as_view(),
        name="create"),
    url(r"new/(?P<slug>[-\w]+)/$", views.CreatePost.as_view(),
        name="create"),
    url(r"by/(?P<username>[-\w]+)/$", views.UserPosts.as_view(),
        name="for_user"),
    url(r"by/(?P<username>[-\w]+)/(?P<pk>\d+)/$", views.PostDetail.as_view(),
        name="single"),
    url(r"delete/(?P<pk>\d+)/$", views.DeletePost.as_view(),
        name="delete"),
]

simplesocial/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

from . import views

urlpatterns = [
    url(r"^$", views.WelcomeView.as_view(), name="home"),
    url(r"^thanks/$", views.ThanksPage.as_view(), name="thanks"),
    url(r"^admin/", admin.site.urls),
    url(r"^accounts/", include("accounts.urls", namespace="accounts")),
    url(r"^accounts/", include("django.contrib.auth.urls")),
    url(r"^posts/", include("posts.urls", namespace="posts")),
    url(r"^groups/", include("groups.urls", namespace="groups")),
    url(r"^tech_news/", include("tech_news.urls", namespace="tech_news")),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r"^rest_api/", include("rest_api.urls", namespace="rest_api"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tech_news/urls.py
from django.conf.urls import url

from . import views

app_name = 'tech_news'

urlpatterns = [
    url(r'^news_main/', views.NewsMainPage.as_view(), name='news-main'),
    url(r'^news_generate/$', views.news_generate, name='news-generate')
]

tech_news/views.py
import requests
from constants import NEWS_SOURCE_DATA_ALL
from decouple import config
from django.http import JsonResponse
from django.shortcuts import render
from django.views import View

API_KEY_NEWS = config('API_KEY_NEWS', cast=str)


# Create your views here.

class NewsMainPage(View):
    def get(self, request):
        default_news_source = NEWS_SOURCE_DATA_ALL['Wired']
        url = ('https://newsapi.org/v2/top-headlines?sources={}&apiKey={}'.format(
            default_news_source['api_name'],
            API_KEY_NEWS))
        response = requests.get(url)
        ctx = {
            'response': response.json()['articles'],
        }
        return render(request,
                      template_name='tech_news/news_main.html',
                      context=ctx)


def news_generate(request):
    news_source = request.GET.get('news_source', None)
    news_source_data_single = {}
    for news_source_key, news_source_values in NEWS_SOURCE_DATA_ALL.items():
        if news_source == news_source_key:
            news_source_data_single = news_source_values
    url = ('https://newsapi.org/v2/top-headlines?sources={}&apiKey={}'.format(
        news_source_data_single['api_name'],
        API_KEY_NEWS))
    response = requests.get(url)
    data = {
        'news_source': news_source_data_single['name'],
        'image_url': news_source_data_single['image_url'],
        'articles': response.json()['articles']
    }
    return JsonResponse(data)

tech_news/templates/tech_news/news_main.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block javascript %}
    <script>
        var news_field = $("#news_field");
        var title_card = $("#title-card");
        $(".ajax_button").click(function () {
            var news_source = $(this).text();
            $.ajax({
                url: '{% url "tech_news:news-generate" %}',
                data: {
                    'news_source': news_source
                },
                dataType: 'json',
                success: function (data) {
                    news_field.empty();
                    title_card.empty();
                    var news_source = data.news_source;
                    var image_url = data.image_url;
                    var all_news = data.articles;
                    title_card.append('<img id="image_url_field" class="news-img-content" src="'
                        + image_url + '"alt="\'No image" style=\'float:left\'>\n' +
                        '            <h1 class="card-text">Tech News</h1>\n' +
                        '            <h1 id="news_source_title_field" class="card-text">'
                        + news_source + '</h1>');
                    for (var i = 0; i < all_news.length; i++) {
                        var single_news = '<h5 class="card-header">' + all_news[i].title + '</h5>\n' +
                            '            <div class="card-body">\n' +
                            '                <img class="news-img-content" src="' + all_news[i].urlToImage + '" alt="\'No image">\n' +
                            '                <p class="card-text card-description">' + all_news[i].description + '</p>\n' +
                            '            </div>\n' +
                            '            <div class="card-footer text-muted">\n' +
                            '                <a href="' + all_news[i].description +
                            '" class="btn btn-primary btn-block hvr-float-shadow">Read news</a>\n</div>';
                        news_field.append(single_news);
                    }
                }
            });
        });
    </script>
{% endblock %}

{% block content %}
    <div class="card">
        <div id="title-card" class="card-body">
            <img id="image_url_field" class="news-img"
                 src="{% static 'tech_news/img/polygon.png' %}" alt="'No image">
            <h1 class="card-text">Tech News</h1>
            <h1 id="news_source_title_field" class="card-text">Polygon</h1>
        </div>
        <div class="card-footer text-muted">
            <a href="#"
               class="ajax_button btn btn-primary" role="button"
               style="width: 22%">Polygon</a>
            <a href="#"
               class="ajax_button btn btn-primary"
               role="button" style="width: 22%">Wired</a>
            <a href="#"
               class="ajax_button btn btn-primary" role="button" style="width: 22%">The Verge</a>
            <a href="#"
               class="ajax_button btn btn-primary" role="button"
               style="width: 22%">TechRadar</a>
        </div>
    </div>
    {% for item in response %}
        <div id="news_field" class="card">
            <h5 class="card-header">{{ item.title }}</h5>
            <div class="card-body">
                <img class="news-img-content" src="{{ item.urlToImage }}" alt="'No image">
                <p class="card-text card-description">{{ item.description }}</p>
            </div>
            <div class="card-footer text-muted">
                <a href="{{ item.url }}" class="btn btn-primary btn-block hvr-float-shadow">Read news</a>
            </div>
        </div>
    {% endfor %}
{% endblock %}