accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r'login/$', auth_views.LoginView.as_view(
        template_name='accounts/login.html'),
        name='login'),
    url(r'logout/$', auth_views.LogoutView.as_view(),
        name='logout'),
    url(r'signup/$', views.SignUp.as_view(),
        name='signup'),
    url(r'user_details/$', views.UserDetails.as_view(),
        name='user_details')
]

posts/urls.py
from django.conf.urls import url

from . import views

app_name = 'posts'

urlpatterns = [
    url(r"^$", views.PostList.as_view(),
        name="all"),
    url(r"new/$", views.CreatePost.as_view(),
        name="create"),
    url(r"new/(?P<slug>[-\w]+)/$", views.CreatePost.as_view(),
        name="create"),
    url(r"by/(?P<username>[-\w]+)/$", views.UserPosts.as_view(),
        name="for_user"),
    url(r"by/(?P<username>[-\w]+)/(?P<pk>\d+)/$", views.PostDetail.as_view(),
        name="single"),
    url(r"delete/(?P<pk>\d+)/$", views.DeletePost.as_view(),
        name="delete"),
]

rest_api/urls.py
from django.conf.urls import url, include
from rest_framework import routers

from . import views

app_name = 'rest_api'

router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet, 'users')
router.register(r'groups', views.GroupViewSet, 'groups')
router.register(r'posts', views.PostViewSet, 'posts')

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.


urlpatterns = [
    url(r'^', include(router.urls)),
    url(r'^api-main/', views.RestApiMain.as_view(), name='api-main'),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
]

simplesocial/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

from . import views

urlpatterns = [
    url(r"^$", views.WelcomeView.as_view(), name="home"),
    url(r"^thanks/$", views.ThanksPage.as_view(), name="thanks"),
    url(r"^admin/", admin.site.urls),
    url(r"^accounts/", include("accounts.urls", namespace="accounts")),
    url(r"^accounts/", include("django.contrib.auth.urls")),
    url(r"^posts/", include("posts.urls", namespace="posts")),
    url(r"^groups/", include("groups.urls", namespace="groups")),
    url(r"^tech_news/", include("tech_news.urls", namespace="tech_news")),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r"^rest_api/", include("rest_api.urls", namespace="rest_api"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tech_news/urls.py
from django.conf.urls import url

from . import views

app_name = 'tech_news'

urlpatterns = [
    url(r'^news_main/', views.NewsMainPage.as_view(), name='news-main'),
    url(r'^news_generate/$', views.news_generate, name='news-generate')
]

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Tech-Hub</title>
    <link rel="icon" type="image/png" href="{% static 'img/logo.png' %}"/>
    <script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'css/master.css' %}">
</head>
<body>

<div class="container">
    <nav class="navbar fixed-top navbar-expand-lg navbar-dark">
        <div class="container">
            <a class="navbar-brand mynav" href="{% url 'home' %}">
                <img class="logo-img" src="{% static 'img/logo_top.png' %} " alt="'No image" style='float:left'></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01"
                    aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
                <ul class="navbar-nav ml-auto">
                    {% if user.is_authenticated %}
                        <li class="nav-item"><a href="{% url 'tech_news:news-main' %}"
                                                class="nav-link btn btn-primary">News</a></li>
                        <li class="nav-item"><a href="{% url 'posts:create' %}"
                                                class="nav-link btn btn-primary">Post</a></li>
                        <li class="nav-item"><a href="{% url 'groups:all' %}"
                                                class="nav-link btn btn-primary">Groups</a></li>
                        <li class="nav-item"><a href="{% url 'rest_api:api-main' %}"
                                                class="nav-link btn btn-primary">API</a></li>
                        <li class="nav-item"><a href="{% url 'accounts:user_details' %}"
                                                class="nav-link btn btn-primary">User: {{ user.get_username }}</a></li>
                        <li class="nav-item"><a href="{% url 'accounts:logout' %}" class="nav-link btn btn-primary">Log
                            out</a></li>
                    {% else %}
                        <li class="nav-item"><a href="{% url 'tech_news:news-main' %}"
                                                class="nav-link btn btn-primary">News</a></li>
                        <li class="nav-item"><a href="{% url 'groups:all' %}"
                                                class="nav-link btn btn-primary">Groups</a></li>
                        <li class="nav-item"><a href="{% url 'accounts:login' %}" class="nav-link btn btn-primary">Log
                            in</a></li>
                        <li class="nav-item"><a href="{% url 'accounts:signup' %}" class="nav-link btn btn-primary">Sign
                            up</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
</div>

<div class="container mycontent">
    {% block content %}
    {% endblock %}
</div>

<!-- Optional JavaScript -->
<!-- Popper.js, then Bootstrap JS -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>

{% block javascript %}
{% endblock %}
</body>
</html>

templates/index.html
{% extends "base.html" %}
{% block content %}

<h1>Welcome to Tech Hub!</h1>
<h2>The best community for all things on outer space!</h2>
<h2>Login or Sign-up for free to get started!</h2>

{% endblock %}

templates/thanks.html
{% extends 'base.html' %}
{% block content %}
    <div class="card" style="width: 100%">
        <div class="card-body">
            <h3>Thanks for visiting!</h3>
        </div>
        <div class="card-footer text-muted">
            <h3 class="card-footer-text">Come back soon!</h3>
        </div>
    </div>
{% endblock %}

templates/welcome_page.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <div class="card">
        <div class="card-body">
            <img class="news-img" src="{% static 'img/logo.png' %} " alt="'No image">
            {% if user.is_authenticated %}
                <h1 class="card-text">Welcome {{ user.get_username }}!</h1>
            {% else %}
                <h1 class="card-text">Welcome to Tech-Hub!</h1>
            {% endif %}
        </div>
        <div class="card-footer text-muted">
            <h3 class="card-footer-text">News of the day</h3>
        </div>
    </div>
    <div class="card">
        <h5 class="card-header">{{ response.title }}</h5>
        <div class="card-body">
            <img class="news-img" src="{{ response.urlToImage }}" alt="'No image">
            <p class="card-text card-description">{{ response.description }}</p>
        </div>
        <div class="card-footer text-muted">
            <a href="{{ response.url }}" class="btn btn-primary btn-block hvr-float-shadow">Read news</a>
        </div>
    </div>
{% endblock %}