posts/urls.py
from django.conf.urls import url

from . import views

app_name = 'posts'

urlpatterns = [
    url(r"^$", views.PostList.as_view(),
        name="all"),
    url(r"new/$", views.CreatePost.as_view(),
        name="create"),
    url(r"new/(?P<slug>[-\w]+)/$", views.CreatePost.as_view(),
        name="create"),
    url(r"by/(?P<username>[-\w]+)/$", views.UserPosts.as_view(),
        name="for_user"),
    url(r"by/(?P<username>[-\w]+)/(?P<pk>\d+)/$", views.PostDetail.as_view(),
        name="single"),
    url(r"delete/(?P<pk>\d+)/$", views.DeletePost.as_view(),
        name="delete"),
]

simplesocial/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

from . import views

urlpatterns = [
    url(r"^$", views.WelcomeView.as_view(), name="home"),
    url(r"^thanks/$", views.ThanksPage.as_view(), name="thanks"),
    url(r"^admin/", admin.site.urls),
    url(r"^accounts/", include("accounts.urls", namespace="accounts")),
    url(r"^accounts/", include("django.contrib.auth.urls")),
    url(r"^posts/", include("posts.urls", namespace="posts")),
    url(r"^groups/", include("groups.urls", namespace="groups")),
    url(r"^tech_news/", include("tech_news.urls", namespace="tech_news")),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r"^rest_api/", include("rest_api.urls", namespace="rest_api"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/models.py
import misaka
from django.contrib.auth import get_user_model
from django.core.urlresolvers import reverse
from django.db import models
from groups.models import Group

User = get_user_model()


class Post(models.Model):
    user = models.ForeignKey(User, related_name="posts")
    created_at = models.DateTimeField(auto_now=True)
    message = models.TextField()
    message_html = models.TextField(editable=False)
    group = models.ForeignKey(Group, related_name="posts", null=True, blank=True)
    image = models.ImageField(upload_to='images/', null=True)

    def __str__(self):
        return self.message

    def save(self, *args, **kwargs):
        self.message_html = misaka.html(self.message)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse(
            "groups:single",
            kwargs={
                "slug": self.group.slug,
            }
        )

    class Meta:
        ordering = ["-created_at"]
        unique_together = ["user", "message"]

posts/forms.py
from django.forms import (Form, CharField, Textarea, ModelChoiceField, ImageField, Select)
from groups.models import Group
from posts import models


class PostForm(Form):
    group = ModelChoiceField(queryset=Group.objects.all(), widget=Select)
    message = CharField(widget=Textarea, required=False)
    image = ImageField(required=False)

    def __init__(self, *args, **kwargs):
        user = kwargs.pop("user", None)
        super().__init__(*args, **kwargs)
        if user is not None:
            self.fields["group"].queryset = (
                models.Group.objects.filter(
                    pk__in=user.groups.values_list("group__pk")
                )
            )

posts/views.py
from braces.views import SelectRelatedMixin
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse_lazy, reverse
from django.http import HttpResponseRedirect, Http404
from django.shortcuts import render
from django.views import View, generic
from groups.models import Group

from .forms import PostForm
from .models import Post

User = get_user_model()


class PostList(SelectRelatedMixin, generic.ListView):
    model = Post
    select_related = ("user", "group")


class UserPosts(generic.ListView):
    model = Post
    template_name = "posts/user_post_list.html"

    def get_queryset(self):
        try:
            self.post_user = User.objects.prefetch_related("posts").get(
                username__iexact=self.kwargs.get("username")
            )
        except User.DoesNotExist:
            raise Http404
        else:
            return self.post_user.posts.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["post_user"] = self.post_user
        return context


class PostDetail(SelectRelatedMixin, generic.DetailView):
    model = Post
    select_related = ("user", "group")

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(
            user__username__iexact=self.kwargs.get("username")
        )


class CreatePost(LoginRequiredMixin, View):

    def get(self, request, slug=None):
        if slug:
            group = Group.objects.get(slug=slug)
            form = PostForm(initial={'group': group})
        else:
            form = PostForm()
        ctx = {'form': form}

        return render(request,
                      template_name='posts/create_post.html',
                      context=ctx)

    def post(self, request):
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            group = form.cleaned_data['group']
            message = form.cleaned_data['message']
            image = form.cleaned_data['image']
            user = self.request.user

            if Post.objects.filter(message=message).exists():
                return HttpResponseRedirect('/object_already_exist')

            Post.objects.create(group=group,
                                message=message,
                                user=user,
                                image=image)
            return HttpResponseRedirect(reverse('groups:single', kwargs={"slug": group.slug}))
        return HttpResponseRedirect('/wrong_value')


class DeletePost(LoginRequiredMixin, SelectRelatedMixin, generic.DeleteView):
    model = Post
    select_related = ("user", "group")
    success_url = reverse_lazy("groups:all")

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user_id=self.request.user.id)

    def delete(self, *args, **kwargs):
        messages.success(self.request, "Post Deleted")
        return super().delete(*args, **kwargs)

posts/templates/posts/_post.html
{% load staticfiles %}
<div id="news_field" class="card">
    <div class="card-body">
        <div class="row">
            <div class="col col-md-4 post-img-info">
                <div class="row post-img">
                    {% if post.image %}
                        <img class="news-img" src="{{ post.image.url }}" alt="'No image">
                    {% else %}
                        <img class="news-img" src="{% static 'img/logo.png' %}" alt="'No image">
                    {% endif %}
                </div>
                <div class="row post-info">
                    <h5><span class="username"><a href="{% url 'posts:for_user' username=post.user.username %}">
                @{{ post.user.username }}</a></span>
                        <time class="time"><a
                                href="{% url 'posts:single' username=post.user.username pk=post.pk %}">{{ post.created_at }}</a>
                        </time>
                    </h5>
                </div>
            </div>
            <div class="col col-md-6">
                <p class="card-text">{{ post.message_html|safe }}</p>
            </div>
        </div>

    </div>
    {% if user.is_authenticated and post.user == user and not hide_delete %}
        <div class="card-footer text-muted">
            <a href="{% url 'posts:delete' pk=post.pk %}" title="delete" class="btn btn-primary btn-block">
                Delete
            </a>
        </div>
    {% endif %}
</div>

posts/templates/posts/create_post.html
{% extends 'groups/group_base.html' %}
{% load static %}
{% load bootstrap4 %}
{% block content %}
    <div class="card">
        <div class="card-body">
            <img class="news-img" src="{%  static 'img/logo.png' %}" alt="'No image"
                 style='float:left'>
            <h1>Create A New Post</h1>
        </div>
    </div>
    <div class="card">
        <div class="card-body">
            <form action="{% url 'posts:create' %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {% bootstrap_form form %}
                <input type="submit" value="Post" class="btn btn-primary btn-lg btn-block">
            </form>
        </div>
    </div>
{% endblock %}

posts/templates/posts/post_base.html
{% extends "base.html" %}

{% block content %}
    <div class="posts-page">
        <div class="container">
            <div class="row">
                {% block prepost %}{% endblock %}
                {% block post_content %}{% endblock %}
                {% block post_post %}{% endblock %}
            </div>
        </div>
    </div>
{% endblock %}

posts/templates/posts/post_confirm_delete.html
{% extends "posts/post_base.html" %}
{% load staticfiles %}
{% block post_content %}
    <div class="card" style="width: 100%">
        <div class="card-body">
            <img class="news-img" src="{% static 'img/logo.png' %}" alt="'No image">
            <h1>Are you sure you want to delete this post?</h1>
        </div>
        <div class="card-footer text-muted">
            <form method="POST">
                {% csrf_token %}
                <input type="submit" value="Confirm Delete" class="btn btn-danger btn-large">
                <a href="{% url 'posts:single' username=user.username pk=object.pk %}"
                   class="btn btn-simple btn-large btn-success">Cancel</a>
            </form>
        </div>
    </div>
{% endblock %}

posts/templates/posts/post_detail.html
{% extends "posts/post_base.html" %}

{% block post_content %}
    <div class="col-md-8">
        {% include "posts/_post.html" %}
    </div>
{% endblock %}

posts/templates/posts/post_list.html
{% extends "posts/post_base.html" %}
{% load humanize %}

{% block pre_post_content %}
    <div class="col-md-4">
        {% if request.user.is_authenticated %}
            <div class="card card-with-shadow">
                <div class="content">
                    <h5 class="title">Your Groups</h5>
                    <ul class="list-unstyled">
                        {% for member_group in get_user_groups %}
                            <li class="group li-with-bullet">
                                <a href="{% url 'groups:single' slug=member_group.group.slug %}">{{ member_group.group.name }}</a>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        {% endif %}
        <div class="card card-with-shadow">
            <div class="content">
                <h5 class="title">All groups</h5>
                <ul class="list-unstyled">
                    {% for other_group in get_other_groups %}
                        <li class="group li-with-bullet"><a
                                href="{% url 'groups:single' slug=other_group.slug %}">{{ other_group.name }}</a></li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
{% endblock %}
{% block post_content %}
    <div class="col-md-8">
        {% for post in post_list %}
            {% include "posts/_post.html" %}
        {% endfor %}
    </div>
{% endblock %}

posts/templates/posts/user_post_list.html
{% extends "posts/post_base.html" %}

{% block prepost %}
    <div class="col-md-4">
        <h1>@{{ post_user.username }}</h1>
        <p>Post History</p>
    </div>
{% endblock %}

{% block post_content %}
    <div class="col-md-8">
        {% for post in post_list %}
            {% include "posts/_post.html" %}
        {% endfor %}
    </div>
{% endblock %}